# this yaml file holds the configuration of the storage positions (boxes of shelf positions)
# these are defined relative to the map frame, and are used to navigate the robot to the desired position
# the positions have to be set up after our convention (x to the corridor, y to the shelf, z to the height, only z rotation)

desk_test:
  position:
    x: -5.0
    y: -2.4
    z: 1.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
    